plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.binary.compatibility.validator)
    alias(libs.plugins.maven.publish) apply false
}

apiValidation {
    ignoredProjects += setOf("sample-app")
    nonPublicMarkers += setOf("io.squarescreen.core.ExperimentalSquareScreenApi")
}

// Register GitHub Packages as a publish target for all submodules that apply the
// maven-publish plugin. The task `publishAllPublicationsToGitHubPackagesRepository`
// is automatically generated by Gradle for a repository named "GitHubPackages".
subprojects {
    afterEvaluate {
        extensions.findByType(org.gradle.api.publish.PublishingExtension::class.java)?.apply {
            repositories {
                maven {
                    name = "GitHubPackages"
                    url = uri("https://maven.pkg.github.com/Perpectiv-Global/square-screen-android-sdk")
                    credentials {
                        username = project.findProperty("githubPackagesUsername") as String? ?: ""
                        password = project.findProperty("githubPackagesPassword") as String? ?: ""
                    }
                }
            }

        // Dokka crashes with "PermittedSubclasses requires ASM9" when reading sealed
        // class bytecode from dependency JARs compiled with Java 17. Fix: sever the
        // dependency between the javadoc Jar task and the Dokka generation task so
        // the jar runs with no inputs and produces an empty (but valid) javadoc jar.
        // Maven Central accepts empty javadoc jars for Android/Kotlin libraries.
        tasks.matching { it.name == "javaDocReleaseJar" }.configureEach {
            setDependsOn(listOf<Any>())
        }
        }
    }
}
